# Generated by Django 3.2.16 on 2022-11-25 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'отзыв', 'verbose_name_plural': 'отзывы'},
        ),
        migrations.AddField(
            model_name='feedback',
            name='mail',
            field=models.EmailField(default='nomail@nomail.com', max_length=150, verbose_name='почта'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='name',
            field=models.CharField(default='пользователь', help_text='Максимальная длина 100 символов', max_length=100, verbose_name='имя пользователя'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='text',
            field=models.CharField(help_text='Максимальная длина 300 символов', max_length=300, verbose_name='отзыв'),
        ),
    ]
