# Generated by Django 3.2.16 on 2022-11-25 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_auto_20221125_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='mail',
            field=models.EmailField(default='mail@mail.com', max_length=150, verbose_name='почта'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.CharField(help_text='Максимальная длина 100 символов', max_length=100, verbose_name='имя пользователя'),
        ),
    ]
