# Generated by Django 3.2.16 on 2022-11-02 15:01

import django.db.models.deletion
from django.db import migrations, models

import catalog.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Максимальная длина - 150 символов', max_length=150, unique=True, verbose_name='название')),
                ('is_published', models.BooleanField(default=True, verbose_name='опубликовано')),
                ('slug', models.SlugField(help_text='Максимум 200 символов', max_length=200)),
                ('weight', models.PositiveSmallIntegerField(default=100)),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
                'ordering': ('weight', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Максимальная длина - 150 символов', max_length=150, unique=True, verbose_name='название')),
                ('is_published', models.BooleanField(default=True, verbose_name='опубликовано')),
                ('slug', models.SlugField(help_text='Максимум 200 символов', max_length=200)),
            ],
            options={
                'verbose_name': 'тег',
                'verbose_name_plural': 'теги',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, verbose_name='опубликовано')),
                ('name', models.CharField(help_text='Максимальная длина - 150 символов', max_length=150, verbose_name='название')),
                ('text', models.TextField(help_text='Не забудьте указать роскошные и превосходные стороны', validators=[catalog.validators.amazing_validator], verbose_name='описание')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.category', verbose_name='категория')),
                ('tags', models.ManyToManyField(related_name='items', to='catalog.Tag', verbose_name='тег')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
                'default_related_name': 'items',
            },
        ),
    ]
