# Generated by Django 3.2.16 on 2022-10-31 15:13

from django.db import migrations, models

import catalog.validators


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.TextField(validators=[catalog.validators.AmazingValidator('прекрасно', 'роскошно')], verbose_name='Описание'),
        ),
    ]
