# Generated by Django 3.2.16 on 2022-10-31 00:38

import catalog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.TextField(validators=[catalog.validators.AmazingValidator.call], verbose_name='Описание'),
        ),
    ]
