# Generated by Django 3.2.16 on 2022-11-20 18:25

import django_quill.fields
from django.db import migrations, models

import catalog.validators


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20221114_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='is_on_main',
            field=models.BooleanField(default=False, help_text='Отображается ли в списке товаров на главной странице', verbose_name='на главной'),
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=django_quill.fields.QuillField(help_text='Не забудьте указать роскошные и превосходные стороны', validators=[catalog.validators.amazing_validator], verbose_name='описание'),
        ),
    ]
