# Generated by Django 3.2.16 on 2022-11-25 15:11

import catalog.validators
from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20221120_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='text',
            field=django_quill.fields.QuillField(help_text='Не забудьте указать роскошные и превосходные стороны', validators=[catalog.validators.amazing_validator], verbose_name='описание'),
        ),
    ]
