# Generated by Django 3.2.16 on 2022-11-25 15:13

import django_quill.fields
from django.db import migrations

import catalog.validators


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_item_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='text',
            field=django_quill.fields.QuillField(help_text='Не забудьте указать роскошные и превосходные стороны', validators=[catalog.validators.amazing_validator], verbose_name='описание'),
        ),
    ]
